# Generated by Django 5.2.3 on 2025-06-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.AddField(
            model_name='profile',
            name='height_ft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_in',
            field=models.IntegerField(default=0),
        ),
    ]
