# Generated by Django 5.2.3 on 2025-07-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_meal_category_alter_meal_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='description',
            new_name='instructions',
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
