# Generated by Django 5.2.3 on 2025-07-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_description_meal_instructions_meal_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='fiber',
            field=models.IntegerField(default=0),
        ),
    ]
