# Generated by Django 5.2.3 on 2025-07-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_meal_fiber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ManyToManyField(related_name='meals', to='users.category'),
        ),
    ]
