# Generated by Django 5.2.3 on 2025-07-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_category_mealtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='category',
            new_name='mealType',
        ),
    ]
