# Generated by Django 5.2.3 on 2025-07-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_category_meal_mealtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='users.profile'),
        ),
    ]
