# Generated by Django 5.2.3 on 2025-07-16 18:34

from django.db import migrations

def create_mealtypes(apps, schema_editor):
    MealType = apps.get_model('users', 'MealType')
    for name in ["Breakfast", "Lunch", "Dinner","Snack"]:
        MealType.objects.get_or_create(name=name)
        
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_meallog'),
    ]

    operations = [
        migrations.RunPython(create_mealtypes)
    ]
